# Generated by Django 3.0 on 2019-12-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatmessages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='room_ref',
        ),
    ]
